/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package erpgest.panels;

import erpgest.MainFrame;
import erpgest.db.DbConn;
import erpgest.utils.Utils;
import java.awt.event.ActionEvent;
import java.awt.event.ItemEvent;
import java.awt.event.ItemListener;
import java.awt.event.KeyEvent;
import java.sql.ResultSet;
import java.util.HashMap;
import java.util.Map;
import javax.swing.AbstractAction;
import javax.swing.Action;
import javax.swing.JComponent;
import javax.swing.JOptionPane;
import javax.swing.KeyStroke;

/**
 *
 * @author SteVid <www.stevid.it>
 */
public class JDialogImpostaPrezzoPerOrdini extends javax.swing.JDialog implements InterfaceCallBackListino{

    MainFrame parentFrame;
    InterfaceCallBackListino parentPanel;    
    String idArticolo = "";
    String idListino = "";
    private Map<String, String> listiniMap = new HashMap<String, String>();
    /**
     * Creates new form JDialogImpostaPrezzo
     */
    public JDialogImpostaPrezzoPerOrdini(MainFrame parent,InterfaceCallBackListino parentPanel,String idArticolo,String nomeArticolo,
            String descrizioneArticolo) {
        super(parent, "Imposta Prezzo Articolo", true);
        this.parentFrame = parent;
        this.parentPanel = parentPanel;        
        initComponents();

        this.idArticolo = idArticolo;
        this.idListino = idListino;
        jLabelNomeArticolo.setText(nomeArticolo);
        jLabelPrezzoArticolo.setText("");        
        jLabelDescrizioneArticolo.setText(descrizioneArticolo);
        
        popolaComboListini();
        jComboBoxListini.addItemListener(new ItemChangeListener());
        
        KeyStroke escape = KeyStroke.getKeyStroke(KeyEvent.VK_ESCAPE, 0, false);
        Action escapeAction = new AbstractAction() {
            public void actionPerformed(ActionEvent e) {
                dispose();
            }
        };
        getRootPane().getInputMap(JComponent.WHEN_IN_FOCUSED_WINDOW).put(escape, "ESCAPE");
        getRootPane().getActionMap().put("ESCAPE", escapeAction);        

        erpgest.utils.UtilsGen.centraDialogo(parent, this);
        setVisible(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabelNomeArticolo = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabelprezzo = new javax.swing.JLabel();
        jLabelPrezzoArticolo = new javax.swing.JLabel();
        jButtonOK = new javax.swing.JButton();
        jButtonCancella = new javax.swing.JButton();
        jLabelDescrizioneArticolo = new javax.swing.JLabel();
        jComboBoxListini = new javax.swing.JComboBox();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(441, 340));
        setResizable(false);
        getContentPane().setLayout(null);

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Scegli Prezzo Articolo"));
        jPanel1.setLayout(null);

        jLabel1.setFont(new java.awt.Font("Trebuchet MS", 1, 12)); // NOI18N
        jLabel1.setText("Listino: ");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(150, 40, 60, 15);

        jLabel3.setFont(new java.awt.Font("Trebuchet MS", 1, 12)); // NOI18N
        jLabel3.setText("Nome Articolo:");
        jPanel1.add(jLabel3);
        jLabel3.setBounds(110, 70, 100, 15);

        jLabelNomeArticolo.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N
        jLabelNomeArticolo.setText("-");
        jPanel1.add(jLabelNomeArticolo);
        jLabelNomeArticolo.setBounds(210, 70, 160, 20);

        jLabel5.setFont(new java.awt.Font("Trebuchet MS", 1, 12)); // NOI18N
        jLabel5.setText("Descrizione:");
        jPanel1.add(jLabel5);
        jLabel5.setBounds(130, 100, 80, 15);

        jLabelprezzo.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N
        jLabelprezzo.setText("Prezzo :");
        jPanel1.add(jLabelprezzo);
        jLabelprezzo.setBounds(130, 150, 70, 20);

        jLabelPrezzoArticolo.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N
        jLabelPrezzoArticolo.setText("-");
        jPanel1.add(jLabelPrezzoArticolo);
        jLabelPrezzoArticolo.setBounds(200, 150, 160, 20);

        jButtonOK.setText("OK");
        jButtonOK.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonOKActionPerformed(evt);
            }
        });
        jPanel1.add(jButtonOK);
        jButtonOK.setBounds(100, 220, 90, 31);

        jButtonCancella.setText("Cancella");
        jButtonCancella.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCancellaActionPerformed(evt);
            }
        });
        jPanel1.add(jButtonCancella);
        jButtonCancella.setBounds(220, 220, 90, 31);

        jLabelDescrizioneArticolo.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N
        jLabelDescrizioneArticolo.setText("-");
        jPanel1.add(jLabelDescrizioneArticolo);
        jLabelDescrizioneArticolo.setBounds(210, 100, 160, 20);

        jComboBoxListini.setFont(new java.awt.Font("Trebuchet MS", 1, 12)); // NOI18N
        jComboBoxListini.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "-" }));
        jComboBoxListini.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jComboBoxListiniItemStateChanged(evt);
            }
        });
        jPanel1.add(jComboBoxListini);
        jComboBoxListini.setBounds(240, 30, 140, 25);

        getContentPane().add(jPanel1);
        jPanel1.setBounds(10, 10, 420, 300);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonCancellaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCancellaActionPerformed
        dispose();
    }//GEN-LAST:event_jButtonCancellaActionPerformed

    private void jButtonOKActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonOKActionPerformed
        if (((String)jComboBoxListini.getSelectedItem()).equals("-")) {
            JOptionPane.showMessageDialog(parentFrame.getFrame(), "Nessun listino selezionato", "Attenzione", JOptionPane.ERROR_MESSAGE);
            return;
        }
        idListino = Utils.getKeyByValue(listiniMap, (String)jComboBoxListini.getSelectedItem());
        parentPanel.settaListino(idListino, idArticolo,jLabelPrezzoArticolo.getText(),(String)jComboBoxListini.getSelectedItem());
        dispose();
        
    }//GEN-LAST:event_jButtonOKActionPerformed

    private void jComboBoxListiniItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jComboBoxListiniItemStateChanged
        
    }//GEN-LAST:event_jComboBoxListiniItemStateChanged

    /**
     * @param args the command line arguments
     */
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonCancella;
    private javax.swing.JButton jButtonOK;
    private javax.swing.JComboBox jComboBoxListini;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabelDescrizioneArticolo;
    private javax.swing.JLabel jLabelNomeArticolo;
    private javax.swing.JLabel jLabelPrezzoArticolo;
    private javax.swing.JLabel jLabelprezzo;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables

    public void popolaCampi(String idProdotto ,String idListino,String listino, String articolo, String descrizione, String prezzo){
        this.idArticolo = idProdotto;
        this.idListino = idListino;
        jLabelNomeArticolo.setText(articolo);
        jLabelPrezzoArticolo.setText(descrizione);
    
    }
    
    private void popolaComboListini(){
        DbConn conn = new DbConn();
        conn.makeConn();
        jComboBoxListini.removeAllItems();
        jComboBoxListini.addItem("-");
        listiniMap.clear();
        try {
            String query = "SELECT * FROM LISTINI WHERE ATTIVO = 'S'";
            ResultSet res = conn.selectSMS(query);
            while( res.next() ){
                jComboBoxListini.addItem(res.getString("NOME"));
                listiniMap.put(res.getString("ID"), res.getString("NOME"));
            }
        } catch (Exception e) {
            Utils.logError(e, "", true);
        }
        conn.close();        
    
    }
    
    @Override
    public void settaListino(String listino, String prezzo) {
        parentPanel.settaListino(idListino, prezzo);
    }

    @Override
    public void settaListino(String idListino, String idPrezzo, String prezzo,String listino) {
        parentPanel.settaListino(idListino, idPrezzo, prezzo,listino);
    }

    
    
    class ItemChangeListener implements ItemListener{

        @Override
        public void itemStateChanged(ItemEvent event) {
           if (event.getStateChange() == ItemEvent.SELECTED) {
              String item = (String)event.getItem();
               if (item.equals("-")) {
                   return;
               }
              String prezzo = "-";
              String idListino = erpgest.utils.Utils.getKeyByValue(listiniMap, item);
               if (!idListino.equals("") || idListino != null) {
                    DbConn conn = new DbConn();
                    conn.makeConn();

                      try {
                          String query = "SELECT P.PREZZO FROM"
                                  + " PREZZI P,LISTINI L"
                                  + " WHERE "
                                  + " L.ID = " + idListino
                                  + " AND L.ATTIVO = 'S'"
                                  + " AND L.ID = P.ID_LISTINO"
                                  + " AND P.ID_ARTICOLO = " + idArticolo
                                  + " AND P.ATTIVO = 'S'";
                          ResultSet res = conn.selectSMS(query);
                          if (res.next()) {
                              prezzo = res.getString("PREZZO");
                          }

                      } catch (Exception e) {
                          Utils.logError(e, "", true);
                      }

                    conn.close();                   
               }

              
              jLabelPrezzoArticolo.setText(prezzo);
           }
        }       
    }    
    
}
