/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package erpgest.panels;

/**
 *
 * @author SteVid <www.stevid.it>
 */
public class JDialogResocontoOrdine extends javax.swing.JDialog {
    
    String idOrdine = "";
    
    /**
     * Creates new form JDialogResocontoOrdine
     */
    public JDialogResocontoOrdine(java.awt.Frame parent, String idOrdine ,boolean modal) {
        super(parent, modal);
        if (idOrdine.equals("")) {
            return;
        }
        this.idOrdine = idOrdine;
        initComponents();
        this.setVisible(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTableListaArticoliTotale = new javax.swing.JTable();
        jButtonStampa = new javax.swing.JButton();
        jButtonStampa1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(944, 608));
        setMinimumSize(new java.awt.Dimension(944, 608));
        getContentPane().setLayout(null);

        jTableListaArticoliTotale.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "ID", "Nome", "Descrizione", "Tot. Colli", "Tot. "
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, true
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(jTableListaArticoliTotale);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(40, 70, 810, 403);

        jButtonStampa.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N
        jButtonStampa.setIcon(new javax.swing.ImageIcon(getClass().getResource("/erpgest/img/ico/printer.png"))); // NOI18N
        jButtonStampa.setText("Stampa");
        jButtonStampa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonStampaActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonStampa);
        jButtonStampa.setBounds(300, 500, 120, 34);

        jButtonStampa1.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N
        jButtonStampa1.setText("Annulla");
        jButtonStampa1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonStampa1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonStampa1);
        jButtonStampa1.setBounds(440, 500, 120, 34);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonStampaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonStampaActionPerformed
        try {
            System.out.println("VALORE: " + jTableListaArticoliTotale.getModel().getValueAt(jTableListaArticoliTotale.getSelectedRow(), 4).toString());
        } catch (Exception e) {
            System.out.println("NULLA");
        }
        
    }//GEN-LAST:event_jButtonStampaActionPerformed

    private void jButtonStampa1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonStampa1ActionPerformed
        dispose();
    }//GEN-LAST:event_jButtonStampa1ActionPerformed

    /**
     * @param args the command line arguments
     */

    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonStampa;
    private javax.swing.JButton jButtonStampa1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTableListaArticoliTotale;
    // End of variables declaration//GEN-END:variables
}
