/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package erpgest.panels;

/**
 *
 * @author SteVid <www.stevid.it>
 */
public class JPanelListinoPrezzi extends javax.swing.JPanel {

    /**
     * Creates new form JPanelListinoPrezzi
     */
    public JPanelListinoPrezzi() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jTextFieldNomeListino = new javax.swing.JTextField();
        jButton4 = new javax.swing.JButton();

        setBorder(javax.swing.BorderFactory.createTitledBorder("Listino Prezzi"));
        setLayout(null);

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Lista Prodotti"));
        jPanel1.setLayout(null);

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        jPanel1.add(jScrollPane1);
        jScrollPane1.setBounds(20, 40, 820, 220);

        jButton1.setText("Imposta Prezzo");
        jPanel1.add(jButton1);
        jButton1.setBounds(680, 280, 160, 31);

        add(jPanel1);
        jPanel1.setBounds(20, 180, 870, 390);

        jButton2.setText("Scegli Listino");
        add(jButton2);
        jButton2.setBounds(50, 50, 140, 31);

        jButton3.setText("Nuovo");
        add(jButton3);
        jButton3.setBounds(230, 50, 140, 31);

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("-");
        add(jLabel1);
        jLabel1.setBounds(130, 140, 190, 20);

        jLabel2.setText("Listino: ");
        add(jLabel2);
        jLabel2.setBounds(50, 140, 70, 20);
        add(jTextFieldNomeListino);
        jTextFieldNomeListino.setBounds(410, 50, 200, 30);

        jButton4.setText("Salva");
        add(jButton4);
        jButton4.setBounds(650, 50, 68, 31);
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField jTextFieldNomeListino;
    // End of variables declaration//GEN-END:variables
}
