/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package erpgest.panels;

import erpgest.MainFrame;
import erpgest.db.DbConn;
import erpgest.utils.Utils;
import erpgest.utils.ValidatoreCodiceFiscale;
import java.awt.event.KeyAdapter;
import java.awt.event.KeyEvent;
import java.sql.ResultSet;
import java.text.SimpleDateFormat;
import java.util.Calendar;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author SteVid <www.stevid.it>
 */
public class JPanelAnagrafica extends javax.swing.JPanel implements InterfaceCallBackClienti,InterfaceCallBackPuntoVendita{

    SimpleDateFormat formatterData = new SimpleDateFormat("dd/MM/yyyy");
    SimpleDateFormat formatterOre = new SimpleDateFormat("HH:mm");
    SimpleDateFormat formatterOreSecondi = new SimpleDateFormat("HH:mm:ss");
    SimpleDateFormat formatterDataENG = new SimpleDateFormat("yyyy-MM-dd");
    SimpleDateFormat formatterDataAndTimeENG = new SimpleDateFormat("yyyy-MM-dd HH:mm:ss");  
    MainFrame parentFrame ;
    
    String UPDATE_OK = "Aggiornamento effettuato.";
    String INSERT_OK = "Inserimento effettuato.";
    
    public void setParentFrame(MainFrame parent){
        this.parentFrame = parent;
    }
    
    /**
     * Creates new form JPanelAnagrafica
     */
    public JPanelAnagrafica() {
        initComponents();
        
        jTextFieldPartitaIVA.setDocument(new erpgest.utils.JTextFieldLimit(11) );
        
        jTextFieldPartitaIVA.addKeyListener(new KeyAdapter() {
                    public void keyTyped(KeyEvent e) {
                        char vChar = e.getKeyChar();
                        if (!(Character.isDigit(vChar)
                                || (vChar == KeyEvent.VK_BACK_SPACE)
                                || (vChar == KeyEvent.VK_DELETE))) {
                            e.consume();
                        }
                    }
                });         

            jTextFieldCAPAzienda.addKeyListener(new KeyAdapter() {
                    public void keyTyped(KeyEvent e) {
                        char vChar = e.getKeyChar();
                        if (!(Character.isDigit(vChar)
                                || (vChar == KeyEvent.VK_BACK_SPACE)
                                || (vChar == KeyEvent.VK_DELETE))) {
                            e.consume();
                        }
                    }
                });  

            jTextFieldCAPRL.addKeyListener(new KeyAdapter() {
                    public void keyTyped(KeyEvent e) {
                        char vChar = e.getKeyChar();
                        if (!(Character.isDigit(vChar)
                                || (vChar == KeyEvent.VK_BACK_SPACE)
                                || (vChar == KeyEvent.VK_DELETE))) {
                            e.consume();
                        }
                    }
                });         
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonRegistra = new javax.swing.JButton();
        buttonRicerca2 = new javax.swing.JButton();
        buttonRipulisci = new javax.swing.JButton();
        jButtonAggiorna = new javax.swing.JButton();
        buttonNuovoCliente = new javax.swing.JButton();
        jTextFieldID = new javax.swing.JTextField();
        buttonElimina = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jLabel50 = new javax.swing.JLabel();
        jTextFieldIndirizzo = new javax.swing.JTextField();
        jLabel52 = new javax.swing.JLabel();
        jTextFieldTelefonoAzienda = new javax.swing.JTextField();
        jLabel54 = new javax.swing.JLabel();
        jTextFieldCAPAzienda = new javax.swing.JTextField();
        jLabel55 = new javax.swing.JLabel();
        jTextFieldCittaAzienda = new javax.swing.JTextField();
        jLabel51 = new javax.swing.JLabel();
        jTextFieldRagioneSociale = new javax.swing.JTextField();
        jTextFieldFaxAzienda = new javax.swing.JTextField();
        jLabel56 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jTextFieldPartitaIVA = new javax.swing.JTextField();
        jLabel61 = new javax.swing.JLabel();
        jTextFieldModalitaPagamento = new javax.swing.JTextField();
        jLabel60 = new javax.swing.JLabel();
        jTextFieldBanca = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        jLabel49 = new javax.swing.JLabel();
        jTextFieldNomeRL = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jTextFieldCognomeRL = new javax.swing.JTextField();
        jLabel53 = new javax.swing.JLabel();
        jTextFieldCittaRL = new javax.swing.JTextField();
        jLabel20 = new javax.swing.JLabel();
        jTextFieldCF = new javax.swing.JTextField();
        jLabel58 = new javax.swing.JLabel();
        jLabel57 = new javax.swing.JLabel();
        jTextFieldTelefonoRL = new javax.swing.JTextField();
        jTextFieldCAPRL = new javax.swing.JTextField();
        jLabel59 = new javax.swing.JLabel();
        jTextFieldIndirizzoRL = new javax.swing.JTextField();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTablePuntiVendita = new javax.swing.JTable();
        jButtonAggiungiPuntoVendita = new javax.swing.JButton();
        jButtonEliminaPuntoVendita = new javax.swing.JButton();
        jButtonModificaPuntoVendita = new javax.swing.JButton();

        setBorder(javax.swing.BorderFactory.createTitledBorder("Clienti"));
        setLayout(null);

        buttonRegistra.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N
        buttonRegistra.setIcon(new javax.swing.ImageIcon(getClass().getResource("/erpgest/img/ico/disk.png"))); // NOI18N
        buttonRegistra.setText("  Salva");
        buttonRegistra.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonRegistraActionPerformed(evt);
            }
        });
        add(buttonRegistra);
        buttonRegistra.setBounds(370, 40, 120, 30);

        buttonRicerca2.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N
        buttonRicerca2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/erpgest/img/ico/drawer.png"))); // NOI18N
        buttonRicerca2.setText(" Ricerca");
        buttonRicerca2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonRicerca2ActionPerformed(evt);
            }
        });
        add(buttonRicerca2);
        buttonRicerca2.setBounds(260, 40, 110, 30);

        buttonRipulisci.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N
        buttonRipulisci.setIcon(new javax.swing.ImageIcon(getClass().getResource("/erpgest/img/ico/sport_shuttlecock.png"))); // NOI18N
        buttonRipulisci.setText("Azzera Campi");
        buttonRipulisci.setToolTipText("Azzera tutti i dati");
        buttonRipulisci.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonRipulisciActionPerformed(evt);
            }
        });
        add(buttonRipulisci);
        buttonRipulisci.setBounds(490, 40, 150, 30);

        jButtonAggiorna.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N
        jButtonAggiorna.setIcon(new javax.swing.ImageIcon(getClass().getResource("/erpgest/img/ico/arrow_refresh.png"))); // NOI18N
        jButtonAggiorna.setText("Aggiorna");
        jButtonAggiorna.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                jButtonAggiornaMouseReleased(evt);
            }
        });
        add(jButtonAggiorna);
        jButtonAggiorna.setBounds(670, 40, 110, 30);

        buttonNuovoCliente.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N
        buttonNuovoCliente.setIcon(new javax.swing.ImageIcon(getClass().getResource("/erpgest/img/ico/user.png"))); // NOI18N
        buttonNuovoCliente.setText("Nuovo Cliente");
        buttonNuovoCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonNuovoClienteActionPerformed(evt);
            }
        });
        add(buttonNuovoCliente);
        buttonNuovoCliente.setBounds(860, 40, 150, 30);

        jTextFieldID.setEditable(false);
        jTextFieldID.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jTextFieldID.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        add(jTextFieldID);
        jTextFieldID.setBounds(30, 30, 90, 35);

        buttonElimina.setIcon(new javax.swing.ImageIcon(getClass().getResource("/erpgest/img/ico/cancel.png"))); // NOI18N
        buttonElimina.setText("Elimina");
        buttonElimina.setToolTipText("Cancella il cliente indicato");
        buttonElimina.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                buttonEliminaMouseReleased(evt);
            }
        });
        buttonElimina.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonEliminaActionPerformed(evt);
            }
        });
        add(buttonElimina);
        buttonElimina.setBounds(130, 40, 110, 30);

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Dati Azienda"));
        jPanel1.setLayout(null);

        jLabel50.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N
        jLabel50.setText("Indirizzo");
        jPanel1.add(jLabel50);
        jLabel50.setBounds(20, 70, 260, 20);

        jTextFieldIndirizzo.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jTextFieldIndirizzo.setForeground(new java.awt.Color(0, 0, 204));
        jPanel1.add(jTextFieldIndirizzo);
        jTextFieldIndirizzo.setBounds(20, 90, 260, 30);

        jLabel52.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N
        jLabel52.setText("Telefono");
        jPanel1.add(jLabel52);
        jLabel52.setBounds(680, 70, 130, 20);

        jTextFieldTelefonoAzienda.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jTextFieldTelefonoAzienda.setForeground(new java.awt.Color(0, 0, 204));
        jPanel1.add(jTextFieldTelefonoAzienda);
        jTextFieldTelefonoAzienda.setBounds(680, 90, 130, 30);

        jLabel54.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N
        jLabel54.setText("CAP");
        jPanel1.add(jLabel54);
        jLabel54.setBounds(560, 70, 110, 20);

        jTextFieldCAPAzienda.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jTextFieldCAPAzienda.setForeground(new java.awt.Color(0, 0, 204));
        jPanel1.add(jTextFieldCAPAzienda);
        jTextFieldCAPAzienda.setBounds(560, 90, 110, 30);

        jLabel55.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N
        jLabel55.setText("Città");
        jPanel1.add(jLabel55);
        jLabel55.setBounds(290, 70, 260, 20);

        jTextFieldCittaAzienda.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jTextFieldCittaAzienda.setForeground(new java.awt.Color(0, 0, 204));
        jPanel1.add(jTextFieldCittaAzienda);
        jTextFieldCittaAzienda.setBounds(290, 90, 260, 30);

        jLabel51.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N
        jLabel51.setText("Ragione Sociale");
        jPanel1.add(jLabel51);
        jLabel51.setBounds(20, 20, 130, 20);

        jTextFieldRagioneSociale.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jTextFieldRagioneSociale.setForeground(new java.awt.Color(0, 0, 204));
        jPanel1.add(jTextFieldRagioneSociale);
        jTextFieldRagioneSociale.setBounds(20, 40, 260, 30);

        jTextFieldFaxAzienda.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jTextFieldFaxAzienda.setForeground(new java.awt.Color(0, 0, 204));
        jPanel1.add(jTextFieldFaxAzienda);
        jTextFieldFaxAzienda.setBounds(820, 90, 130, 30);

        jLabel56.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N
        jLabel56.setText("FAX");
        jPanel1.add(jLabel56);
        jLabel56.setBounds(820, 70, 130, 20);

        jLabel21.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N
        jLabel21.setText("Partita IVA");
        jPanel1.add(jLabel21);
        jLabel21.setBounds(290, 20, 170, 20);

        jTextFieldPartitaIVA.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jTextFieldPartitaIVA.setForeground(new java.awt.Color(0, 0, 204));
        jPanel1.add(jTextFieldPartitaIVA);
        jTextFieldPartitaIVA.setBounds(290, 40, 170, 30);

        jLabel61.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N
        jLabel61.setText("Modalita Pagamento");
        jPanel1.add(jLabel61);
        jLabel61.setBounds(470, 20, 260, 20);

        jTextFieldModalitaPagamento.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jTextFieldModalitaPagamento.setForeground(new java.awt.Color(0, 0, 204));
        jPanel1.add(jTextFieldModalitaPagamento);
        jTextFieldModalitaPagamento.setBounds(470, 40, 260, 30);

        jLabel60.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N
        jLabel60.setText("Banca d' appoggio");
        jPanel1.add(jLabel60);
        jLabel60.setBounds(750, 20, 260, 20);

        jTextFieldBanca.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jTextFieldBanca.setForeground(new java.awt.Color(0, 0, 204));
        jPanel1.add(jTextFieldBanca);
        jTextFieldBanca.setBounds(750, 40, 260, 30);

        add(jPanel1);
        jPanel1.setBounds(30, 80, 1040, 140);

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder("Referente Legale"));
        jPanel2.setLayout(null);

        jLabel49.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N
        jLabel49.setText("Nome");
        jPanel2.add(jLabel49);
        jLabel49.setBounds(20, 20, 90, 20);

        jTextFieldNomeRL.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jTextFieldNomeRL.setForeground(new java.awt.Color(0, 0, 204));
        jPanel2.add(jTextFieldNomeRL);
        jTextFieldNomeRL.setBounds(20, 40, 260, 30);

        jLabel5.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N
        jLabel5.setText("Cognome");
        jPanel2.add(jLabel5);
        jLabel5.setBounds(290, 20, 100, 20);

        jTextFieldCognomeRL.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jTextFieldCognomeRL.setForeground(new java.awt.Color(0, 0, 204));
        jPanel2.add(jTextFieldCognomeRL);
        jTextFieldCognomeRL.setBounds(290, 40, 280, 30);

        jLabel53.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N
        jLabel53.setText("Città");
        jPanel2.add(jLabel53);
        jLabel53.setBounds(290, 70, 260, 20);

        jTextFieldCittaRL.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jTextFieldCittaRL.setForeground(new java.awt.Color(0, 0, 204));
        jPanel2.add(jTextFieldCittaRL);
        jTextFieldCittaRL.setBounds(290, 90, 260, 30);

        jLabel20.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N
        jLabel20.setText("Codice Fiscale");
        jPanel2.add(jLabel20);
        jLabel20.setBounds(820, 70, 200, 20);

        jTextFieldCF.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jTextFieldCF.setForeground(new java.awt.Color(0, 0, 204));
        jPanel2.add(jTextFieldCF);
        jTextFieldCF.setBounds(820, 90, 200, 30);

        jLabel58.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N
        jLabel58.setText("Telefono");
        jPanel2.add(jLabel58);
        jLabel58.setBounds(680, 70, 130, 20);

        jLabel57.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N
        jLabel57.setText("CAP");
        jPanel2.add(jLabel57);
        jLabel57.setBounds(560, 70, 110, 20);

        jTextFieldTelefonoRL.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jTextFieldTelefonoRL.setForeground(new java.awt.Color(0, 0, 204));
        jPanel2.add(jTextFieldTelefonoRL);
        jTextFieldTelefonoRL.setBounds(680, 90, 130, 30);

        jTextFieldCAPRL.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jTextFieldCAPRL.setForeground(new java.awt.Color(0, 0, 204));
        jPanel2.add(jTextFieldCAPRL);
        jTextFieldCAPRL.setBounds(560, 90, 110, 30);

        jLabel59.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N
        jLabel59.setText("Indirizzo");
        jPanel2.add(jLabel59);
        jLabel59.setBounds(20, 70, 260, 20);

        jTextFieldIndirizzoRL.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jTextFieldIndirizzoRL.setForeground(new java.awt.Color(0, 0, 204));
        jPanel2.add(jTextFieldIndirizzoRL);
        jTextFieldIndirizzoRL.setBounds(20, 90, 260, 30);

        add(jPanel2);
        jPanel2.setBounds(30, 230, 1040, 140);

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder("Punti Vendita"));
        jPanel3.setLayout(null);

        jTablePuntiVendita.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Nome", "Indirizzo", "Citta", "CAP", "Telefono"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, true, true
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(jTablePuntiVendita);
        if (jTablePuntiVendita.getColumnModel().getColumnCount() > 0) {
            jTablePuntiVendita.getColumnModel().getColumn(0).setPreferredWidth(50);
            jTablePuntiVendita.getColumnModel().getColumn(1).setPreferredWidth(200);
            jTablePuntiVendita.getColumnModel().getColumn(2).setPreferredWidth(300);
            jTablePuntiVendita.getColumnModel().getColumn(3).setPreferredWidth(80);
            jTablePuntiVendita.getColumnModel().getColumn(4).setPreferredWidth(60);
            jTablePuntiVendita.getColumnModel().getColumn(5).setPreferredWidth(80);
        }

        jPanel3.add(jScrollPane1);
        jScrollPane1.setBounds(20, 20, 970, 230);

        jButtonAggiungiPuntoVendita.setIcon(new javax.swing.ImageIcon(getClass().getResource("/erpgest/img/ico/add.png"))); // NOI18N
        jButtonAggiungiPuntoVendita.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAggiungiPuntoVenditaActionPerformed(evt);
            }
        });
        jPanel3.add(jButtonAggiungiPuntoVendita);
        jButtonAggiungiPuntoVendita.setBounds(990, 30, 40, 40);

        jButtonEliminaPuntoVendita.setIcon(new javax.swing.ImageIcon(getClass().getResource("/erpgest/img/ico/minus2.png"))); // NOI18N
        jButtonEliminaPuntoVendita.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonEliminaPuntoVenditaActionPerformed(evt);
            }
        });
        jPanel3.add(jButtonEliminaPuntoVendita);
        jButtonEliminaPuntoVendita.setBounds(990, 80, 40, 40);

        jButtonModificaPuntoVendita.setIcon(new javax.swing.ImageIcon(getClass().getResource("/erpgest/img/ico/pencil.png"))); // NOI18N
        jButtonModificaPuntoVendita.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonModificaPuntoVenditaActionPerformed(evt);
            }
        });
        jPanel3.add(jButtonModificaPuntoVendita);
        jButtonModificaPuntoVendita.setBounds(990, 130, 40, 40);

        add(jPanel3);
        jPanel3.setBounds(30, 380, 1040, 270);
    }// </editor-fold>//GEN-END:initComponents

    private void buttonRegistraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonRegistraActionPerformed

        String CAPAzienda     = jTextFieldCAPAzienda.getText().trim().toUpperCase().replaceAll("'", "''");
        String CAPRL          = jTextFieldCAPRL.getText().trim().toUpperCase().replaceAll("'", "''");
        String codiceFiscale  = jTextFieldCF.getText().trim().toUpperCase().replaceAll("'", "''");
        String cittaAzienda   = jTextFieldCittaAzienda.getText().trim().toUpperCase().replaceAll("'", "''");
        String CittaRL        = jTextFieldCittaRL.getText().trim().toUpperCase().replaceAll("'", "''");
        String CognomeRL      = jTextFieldCognomeRL.getText().trim().toUpperCase().replaceAll("'", "''");
        String faxAzienda     = jTextFieldFaxAzienda.getText().trim().toUpperCase().replaceAll("'", "''");
        String indirizzo      = jTextFieldIndirizzo.getText().trim().toUpperCase().replaceAll("'", "''");
        String indirizzoRL    = jTextFieldIndirizzoRL.getText().trim().toUpperCase().replaceAll("'", "''");
        String nomeRL         = jTextFieldNomeRL.getText().trim().toUpperCase().replaceAll("'", "''");
        String partitaIVA     = jTextFieldPartitaIVA.getText().trim().toUpperCase().replaceAll("'", "''");
        String ragioneSociale = jTextFieldRagioneSociale.getText().trim().toUpperCase().replaceAll("'", "''");
        String telefonoAzienda= jTextFieldTelefonoAzienda.getText().trim().toUpperCase().replaceAll("'", "''");
        String telefonoRL     = jTextFieldTelefonoRL.getText().trim().toUpperCase().replaceAll("'", "''");
        String modalitaPagamento = jTextFieldModalitaPagamento.getText().trim().toUpperCase().replaceAll("'", "''");
        String banca          = jTextFieldBanca.getText().trim().toUpperCase().replaceAll("'", "''");
        String id             = jTextFieldID.getText().trim().toUpperCase().replaceAll("'", "''");
        
        //controllo esistenza e validazione
        if( ragioneSociale.equals("") ||
            indirizzo.equals("") ||
            CAPAzienda.equals("") ||
            cittaAzienda.equals("")
                ){
                JOptionPane.showMessageDialog(parentFrame.getFrame(), "Errore Ragione Sociale , indirizzo ,citta e cap dell'azienda, sono obbligatori.", "Attenzione", JOptionPane.ERROR_MESSAGE);
                return;
        }

        if( ( partitaIVA.equals("") && codiceFiscale.equals("") ) ){
                JOptionPane.showMessageDialog(parentFrame.getFrame(), "E' obbligatorio inserire la Partita IVA o il Codice Fiscale", "Attenzione", JOptionPane.ERROR_MESSAGE);
                return;            
        }
        
        if( partitaIVA.equals("00000000000")){
            JOptionPane.showMessageDialog(parentFrame, "Partita iva generica non consentita.", "Attenzione", JOptionPane.ERROR_MESSAGE);
            return;            
        }
        
        if( !partitaIVA.equals("") ){
            
            String idPartitaIvaTrovata = controllaPresenzaPartitaIVA(partitaIVA);
            
            if (idPartitaIvaTrovata.equals("")) {
                String resultPartitaIva = erpgest.utils.Utils.ControllaPIVA(partitaIVA);
                if (!resultPartitaIva.equals("")) {
                    JOptionPane.showMessageDialog(parentFrame, resultPartitaIva, "Attenzione", JOptionPane.ERROR_MESSAGE);
                    closeDialog();
                    return;
                }                     
            }else{
                if (!idPartitaIvaTrovata.equals(id)) {
                    JOptionPane.showMessageDialog(parentFrame, "Partita IVA gia presente id cliente:"+idPartitaIvaTrovata, "Attenzione", JOptionPane.ERROR_MESSAGE);
                    closeDialog();
                    return;                   
                }                        
            }
        }
        
        if( !codiceFiscale.equals("") ){
            if (!erpgest.utils.Utils.validaCF(codiceFiscale)) {
                JOptionPane.showMessageDialog(parentFrame, "CodiceFiscale non Valido", "Attenzione", JOptionPane.ERROR_MESSAGE);
                //closeDialog();
                return;
            }          
        }      
       
        /*
        Calendar cal = Calendar.getInstance();
        String query;
        String strDate = formatterDataAndTimeENG.format(cal.getTime());
        String nomeStr = (jTextFieldNomeRL.getText()).trim().toUpperCase().replaceAll("'", "''");
        String cognomeStr = (jTextFieldCognomeRL.getText()).trim().toUpperCase().replaceAll("'", "''");
        String codiceFiscaleStr = (jTextFieldCF.getText()).trim().toUpperCase().replaceAll("'", "''");


        String returnStr = "";

        ResultSet res = null;
        int i = 0;

        if (nomeStr.equals("")
            || nomeStr == null
            || cognomeStr.equals("")
            || cognomeStr == null //|| codiceFiscaleStr.equals("")
            //|| codiceFiscaleStr == null
        ) {

            JOptionPane.showMessageDialog(parentFrame.getFrame(), "Errore Nome,Cognome sono obbligatori", "Attenzione", JOptionPane.ERROR_MESSAGE);
            parentFrame.closeDialog();
            return;
        }*/
        
        Thread t = new Thread(new erpgest.utils.ShowWaiting(parentFrame.getFrame(), null, "Salvataggio in corso. Attendere"));
        t.start();

        while (parentFrame.waiting == null) {
            try {
                Thread.sleep(100);
            } catch (Exception e) {
            }
        }

        Thread tt = new Thread(new SalvaDatiNelDB());
        tt.start();
    }//GEN-LAST:event_buttonRegistraActionPerformed

    private void buttonRicerca2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonRicerca2ActionPerformed
        JPanelRicercaClienti dialog = new JPanelRicercaClienti(this.parentFrame,this);
    }//GEN-LAST:event_buttonRicerca2ActionPerformed

    private void buttonRipulisciActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonRipulisciActionPerformed
        azzeraCampi();
    }//GEN-LAST:event_buttonRipulisciActionPerformed

    private void jButtonAggiornaMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonAggiornaMouseReleased
        String id = jTextFieldID.getText();
        int _id = 0;
        if (!id.equals("") && !id.equals("-")) {
            _id = Integer.parseInt(id);
        }

        aggiornaFinestraInserimentoCliente(id);
    }//GEN-LAST:event_jButtonAggiornaMouseReleased

    private void buttonNuovoClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonNuovoClienteActionPerformed
        azzeraCampi();
    }//GEN-LAST:event_buttonNuovoClienteActionPerformed

    
    private void closeDialog() {
        if (parentFrame.waiting != null) {
            parentFrame.waiting.dispose();
            parentFrame.waiting = null;
            parentFrame.validate();
            parentFrame.repaint();
        }

    }    
    
    private void buttonEliminaMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_buttonEliminaMouseReleased
        if (jTextFieldID.getText().equals("") || jTextFieldID.getText().equals("-")) {
            JOptionPane.showMessageDialog(this, "Cliente Selezionato Non disponibile o mancante.", "Attenzione", JOptionPane.ERROR_MESSAGE);
            return;
        }
        
        controllaPresenzaCliente(jTextFieldID.getText());
        
        int n = JOptionPane.showConfirmDialog(null,
            "ATTENZIONE!! Si vuole cancellare il cliente "+ jTextFieldRagioneSociale.getText()+" di " 
                    + jTextFieldNomeRL.getText()+","+jTextFieldCognomeRL.getText() +"?",
            "",
            JOptionPane.YES_NO_OPTION);

        if (n == JOptionPane.YES_OPTION) {
            //JOptionPane.showMessageDialog(null, "Opening...");
            disabilitaUtente(jTextFieldID.getText());
        } else {
            //JOptionPane.showMessageDialog(null, "Goodbye");
            return;
        }
    }//GEN-LAST:event_buttonEliminaMouseReleased

    private void buttonEliminaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonEliminaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_buttonEliminaActionPerformed

    private void jButtonAggiungiPuntoVenditaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAggiungiPuntoVenditaActionPerformed
        if ( jTextFieldID.getText().equals("")) {
            JOptionPane.showMessageDialog(this.parentFrame, "Selezionare un cliente.", "ATTENZIONE!", JOptionPane.ERROR_MESSAGE);
            return;
        }
        String idPuntoVendita = "";
        try {
            idPuntoVendita = jTablePuntiVendita.getModel().getValueAt(jTablePuntiVendita.getSelectedRow(), 0).toString();
        } catch (Exception e) {
        }
        
        JDialogImpostaPuntoVendita jDialogImpostaPuntoVendita = new JDialogImpostaPuntoVendita(this.parentFrame,this,jTextFieldID.getText(),idPuntoVendita,false);
    }//GEN-LAST:event_jButtonAggiungiPuntoVenditaActionPerformed

    private void jButtonModificaPuntoVenditaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonModificaPuntoVenditaActionPerformed
        if ( jTextFieldID.getText().equals("")) {
            JOptionPane.showMessageDialog(this.parentFrame, "Selezionare un cliente.", "ATTENZIONE!", JOptionPane.ERROR_MESSAGE);
            return;
        }
        String idPuntoVendita = "";
        try {
            idPuntoVendita = jTablePuntiVendita.getModel().getValueAt(jTablePuntiVendita.getSelectedRow(), 0).toString();
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this.parentFrame, "Selezionare un punto vendita.", "ATTENZIONE!", JOptionPane.ERROR_MESSAGE);
            return;
        }
        
        JDialogImpostaPuntoVendita jDialogImpostaPuntoVendita = new JDialogImpostaPuntoVendita(this.parentFrame,this,jTextFieldID.getText(),idPuntoVendita,true);
    }//GEN-LAST:event_jButtonModificaPuntoVenditaActionPerformed

    private void jButtonEliminaPuntoVenditaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonEliminaPuntoVenditaActionPerformed
        if ( jTextFieldID.getText().equals("")) {
            JOptionPane.showMessageDialog(this.parentFrame, "Selezionare un cliente.", "ATTENZIONE!", JOptionPane.ERROR_MESSAGE);
            return;
        }
        String idPuntoVendita = "";
        try {
            idPuntoVendita = jTablePuntiVendita.getModel().getValueAt(jTablePuntiVendita.getSelectedRow(), 0).toString();
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this.parentFrame, "Selezionare un punto vendita.", "ATTENZIONE!", JOptionPane.ERROR_MESSAGE);
            return;
        }        

        int n = JOptionPane.showConfirmDialog(null,
            "ATTENZIONE!! Si vuole cancellare il punto vendita "+ jTablePuntiVendita.getModel().getValueAt(jTablePuntiVendita.getSelectedRow(), 1).toString()+" di " 
                    + jTablePuntiVendita.getModel().getValueAt(jTablePuntiVendita.getSelectedRow(), 2).toString()+" ?",
            "",
            JOptionPane.YES_NO_OPTION);

        if (n == JOptionPane.YES_OPTION) {
            disabilitaPuntoVendita(jTextFieldID.getText(),idPuntoVendita);
        } else {
            //JOptionPane.showMessageDialog(null, "Goodbye");
            return;
        }        
        

    }//GEN-LAST:event_jButtonEliminaPuntoVenditaActionPerformed
    
    public void aggiornaTabellaPuntiVendita(String id){
        DbConn conn = new DbConn();
        conn.makeConn();
        
        String query = "";
        ResultSet res = null;
        String risultato = "";
        try {
            query = "SELECT * FROM PUNTI_VENDITA "
                    + " WHERE ID_ANAGRAFICA_PADRE = '"+id+"' "
            + " AND ATTIVO = 'S' ORDER BY DATA_MODIFICA DESC";            
            res   = conn.selectSMS(query);
            DefaultTableModel defaultModel = (DefaultTableModel) jTablePuntiVendita.getModel();

            while (defaultModel.getRowCount() > 0) {
                defaultModel.removeRow(0);
            }            
            while (res.next()) {
                Object[] cell = {res.getString("ID"),
                    res.getString("NOME") ,
                    res.getString("INDIRIZZO"),
                    res.getString("CITTA"),
                    res.getString("CAP"),
                    res.getString("TELEFONO")
                };
                defaultModel.addRow(cell);
            }
            jTablePuntiVendita.invalidate();
            jTablePuntiVendita.validate();
            jTablePuntiVendita.repaint();              
            
        } catch (Exception e) {
            Utils.logError(e, "", true);
        }
        conn.close();
    }
    

    public void aggiornaFinestraInserimentoCliente(String id){
        
        DbConn conn = new DbConn();
        conn.makeConn();
        
        try {
            String query = "SELECT * FROM ANAGRAFICA "
                    + " WHERE ID='"+id+"'";
            
            ResultSet res = conn.selectSMS(query);
            
            if( res.next() ){
                jTextFieldCAPAzienda.setText( res.getString("CAP_AZIENDA") );
                jTextFieldCAPRL.setText( res.getString("CAP_RL") );
                jTextFieldCF.setText(res.getString("CODICE_FISCALE"));
                jTextFieldCittaAzienda.setText( res.getString("CITTA_AZIENDA") );
                jTextFieldCittaRL.setText( res.getString("CITTA_RL") );
                jTextFieldCognomeRL.setText( res.getString("COGNOME_RL") );
                jTextFieldFaxAzienda.setText( res.getString("FAX_AZIENDA") );
                jTextFieldIndirizzo.setText( res.getString("INDIRIZZO_AZIENDA") );
                jTextFieldIndirizzoRL.setText( res.getString("INDIRIZZO_RL") );
                jTextFieldNomeRL.setText( res.getString("NOME_RL") );
                jTextFieldPartitaIVA.setText( res.getString("PARTITA_IVA") );
                jTextFieldRagioneSociale.setText( res.getString("RAGIONE_SOCIALE") );
                jTextFieldTelefonoAzienda.setText( res.getString("TELEFONO_AZIENDA") );
                jTextFieldTelefonoRL.setText( res.getString("TELEFONO_RL") );
                jTextFieldBanca.setText( res.getString("BANCA") );
                jTextFieldModalitaPagamento.setText( res.getString("MODALITA_PAGAMENTO") );
                jTextFieldID.setText( res.getString("ID") );            
            
            }
        } catch (Exception e) {
        }
        
        conn.close();
        
        aggiornaListaPuntiVendita(id);
        
        
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton buttonElimina;
    public javax.swing.JButton buttonNuovoCliente;
    public javax.swing.JButton buttonRegistra;
    public javax.swing.JButton buttonRicerca2;
    public javax.swing.JButton buttonRipulisci;
    private javax.swing.JButton jButtonAggiorna;
    private javax.swing.JButton jButtonAggiungiPuntoVendita;
    private javax.swing.JButton jButtonEliminaPuntoVendita;
    private javax.swing.JButton jButtonModificaPuntoVendita;
    public javax.swing.JLabel jLabel20;
    public javax.swing.JLabel jLabel21;
    public javax.swing.JLabel jLabel49;
    public javax.swing.JLabel jLabel5;
    public javax.swing.JLabel jLabel50;
    public javax.swing.JLabel jLabel51;
    public javax.swing.JLabel jLabel52;
    public javax.swing.JLabel jLabel53;
    public javax.swing.JLabel jLabel54;
    public javax.swing.JLabel jLabel55;
    public javax.swing.JLabel jLabel56;
    public javax.swing.JLabel jLabel57;
    public javax.swing.JLabel jLabel58;
    public javax.swing.JLabel jLabel59;
    public javax.swing.JLabel jLabel60;
    public javax.swing.JLabel jLabel61;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTablePuntiVendita;
    public javax.swing.JTextField jTextFieldBanca;
    public javax.swing.JTextField jTextFieldCAPAzienda;
    public javax.swing.JTextField jTextFieldCAPRL;
    public javax.swing.JTextField jTextFieldCF;
    public javax.swing.JTextField jTextFieldCittaAzienda;
    public javax.swing.JTextField jTextFieldCittaRL;
    public javax.swing.JTextField jTextFieldCognomeRL;
    public javax.swing.JTextField jTextFieldFaxAzienda;
    public javax.swing.JTextField jTextFieldID;
    public javax.swing.JTextField jTextFieldIndirizzo;
    public javax.swing.JTextField jTextFieldIndirizzoRL;
    public javax.swing.JTextField jTextFieldModalitaPagamento;
    public javax.swing.JTextField jTextFieldNomeRL;
    public javax.swing.JTextField jTextFieldPartitaIVA;
    public javax.swing.JTextField jTextFieldRagioneSociale;
    public javax.swing.JTextField jTextFieldTelefonoAzienda;
    public javax.swing.JTextField jTextFieldTelefonoRL;
    // End of variables declaration//GEN-END:variables

    private void azzeraCampi() {
        jTextFieldCAPAzienda.setText("");
        jTextFieldCAPRL.setText("");
        jTextFieldCF.setText("");
        jTextFieldCittaAzienda.setText("");
        jTextFieldCittaRL.setText("");
        jTextFieldCognomeRL.setText("");
        jTextFieldFaxAzienda.setText("");
        jTextFieldIndirizzo.setText("");
        jTextFieldIndirizzoRL.setText("");
        jTextFieldNomeRL.setText("");
        jTextFieldPartitaIVA.setText("");
        jTextFieldRagioneSociale.setText("");
        jTextFieldTelefonoAzienda.setText("");
        jTextFieldTelefonoRL.setText("");
        jTextFieldID.setText("");
        jTextFieldBanca.setText("");
        jTextFieldModalitaPagamento.setText("");
    }

    private void disabilitaUtente(String id) {
        DbConn conn = new DbConn();
        conn.makeConn();
        
        try {
            String query = "UPDATE ANAGRAFICA SET ATTIVO = 'N' , DATA_MODIFICA =  datetime('now', 'localtime') WHERE ID = '"+id+"'";
            
            String result = conn.delete(query);
            if( result.equals("Rimozione effettuata.") ){
                    JOptionPane.showMessageDialog(parentFrame.getFrame(), "Cliente eliminato correttamente", "OK", JOptionPane.INFORMATION_MESSAGE);                    
                    azzeraCampi();                    
                    
            }else{
                JOptionPane.showMessageDialog(parentFrame.getFrame(), "Non è stato possibile cancellare l'elemento", "Attenzione", JOptionPane.ERROR_MESSAGE);
            }
            
        } catch (Exception e) {
        }
        conn.close();        
    }
    private boolean controllaPresenzaCliente(String id){
        
        if (id.equals("") || id == null) {
            return false;
        }
        boolean risultato = false;
        DbConn conn = new DbConn();
        conn.makeConn();
        try {
            
            String query = "SELECT COUNT(*) FROM ANAGRAFICA WHERE ID='"+id+"' AND ATTIVO = 'S'";
            ResultSet res = conn.selectSMS(query);
            int count = res.getInt(1);
            if( count > 0 ){
                risultato = true;
            }else
                risultato = false;
            
        } catch (Exception e) {
        }
        
        conn.close();
        return risultato;
    }    
    
    private String controllaPresenzaPartitaIVA(String pIVA){
        
        if (pIVA.equals("") || pIVA == null) {
            return "";
        }
        String risultato = "";
        DbConn conn = new DbConn();
        conn.makeConn();
        try {
            
            String query = "SELECT * FROM ANAGRAFICA WHERE PARTITA_IVA='"+pIVA+"' AND ATTIVO = 'S'";
            ResultSet res = conn.selectSMS(query);
            
            if (res.next()) {
                risultato = res.getString("ID");
            }
            
        } catch (Exception e) {
        }
        
        conn.close();
        return risultato;
    }     

    @Override
    public void aggiornaListaClienti(String id) {
        aggiornaFinestraInserimentoCliente(id);
    }

    @Override
    public void aggiornaListaPuntiVendita(String id) {
        aggiornaTabellaPuntiVendita(id);
    }

    private void disabilitaPuntoVendita(String idAnagraficaPadre, String idPuntoVendita) {
        
        if (idAnagraficaPadre.equals("") || idPuntoVendita.equals("")) {
            return;
        }
        
        DbConn conn = new DbConn();
        conn.makeConn();
        
        String query = "";
        ResultSet res = null;
        String risultato = "";
        try {
            query = "UPDATE PUNTI_VENDITA"
                + " SET ATTIVO = 'N' "
                + " WHERE ID_ANAGRAFICA_PADRE = '"+idAnagraficaPadre+"'"
                + " AND ID = '"+idPuntoVendita+"'";
            risultato = conn.update(query);
            if (!risultato.equals(UPDATE_OK)) {
                JOptionPane.showMessageDialog(this.parentFrame, "Errore in fase di cancellazione.", "ATTENZIONE!", JOptionPane.ERROR_MESSAGE);
            }
        } catch (Exception e) {
            Utils.logError(e, "", true);
        }
        conn.close();
        aggiornaTabellaPuntiVendita(jTextFieldID.getText());        
    }
    
    class SalvaDatiNelDB implements Runnable {

        @Override
        public void run() {
            
            String CAPAzienda     = jTextFieldCAPAzienda.getText().trim().toUpperCase().replaceAll("'", "''");
            String CAPRL          = jTextFieldCAPRL.getText().trim().toUpperCase().replaceAll("'", "''");
            String codiceFiscale  = jTextFieldCF.getText().trim().toUpperCase().replaceAll("'", "''");
            String cittaAzienda   = jTextFieldCittaAzienda.getText().trim().toUpperCase().replaceAll("'", "''");
            String CittaRL        = jTextFieldCittaRL.getText().trim().toUpperCase().replaceAll("'", "''");
            String CognomeRL      = jTextFieldCognomeRL.getText().trim().toUpperCase().replaceAll("'", "''");
            String faxAzienda     = jTextFieldFaxAzienda.getText().trim().toUpperCase().replaceAll("'", "''");
            String indirizzo      = jTextFieldIndirizzo.getText().trim().toUpperCase().replaceAll("'", "''");
            String indirizzoRL    = jTextFieldIndirizzoRL.getText().trim().toUpperCase().replaceAll("'", "''");
            String nomeRL         = jTextFieldNomeRL.getText().trim().toUpperCase().replaceAll("'", "''");
            String partitaIVA     = jTextFieldPartitaIVA.getText().trim().toUpperCase().replaceAll("'", "''");
            String ragioneSociale = jTextFieldRagioneSociale.getText().trim().toUpperCase().replaceAll("'", "''");
            String telefonoAzienda= jTextFieldTelefonoAzienda.getText().trim().toUpperCase().replaceAll("'", "''");
            String telefonoRL     = jTextFieldTelefonoRL.getText().trim().toUpperCase().replaceAll("'", "''");
            String modalitaPagamento = jTextFieldModalitaPagamento.getText().trim().toUpperCase().replaceAll("'", "''");
            String banca          = jTextFieldBanca.getText().trim().toUpperCase().replaceAll("'", "''");            
            String id             = jTextFieldID.getText().trim().toUpperCase().replaceAll("'", "''");
            String query = "";
            String result = "";
            
            ResultSet res = null;
            DbConn conn = new DbConn();
            conn.makeConn();
            
            try {
                if (controllaPresenzaCliente(id)) {
                    //faccio update
                    query = "UPDATE ANAGRAFICA SET "
                            + " CAP_AZIENDA = '"+CAPAzienda+"',"
                            + " CAP_RL = '"+CAPRL+"',"
                            + " CODICE_FISCALE = '"+codiceFiscale+"',"
                            + " CITTA_AZIENDA = '"+cittaAzienda+"',"
                            + " CITTA_RL = '"+CittaRL+"',"
                            + " NOME_RL = '"+nomeRL+"',"
                            + " COGNOME_RL= '"+CognomeRL+"',"
                            + " PARTITA_IVA = '"+partitaIVA+"',"
                            + " FAX_AZIENDA = '"+faxAzienda+"',"
                            + " TELEFONO_RL = '"+telefonoRL+"',"
                            + " TELEFONO_AZIENDA = '"+telefonoAzienda+"',"
                            + " INDIRIZZO_AZIENDA = '"+indirizzo+"',"
                            + " INDIRIZZO_RL = '"+indirizzoRL+"',"
                            + " RAGIONE_SOCIALE = '"+ragioneSociale+"',"
                            + " DATA_MODIFICA = datetime('now', 'localtime') ,"
                            + " BANCA = '"+banca+"',"
                            + " MODALITA_PAGAMENTO = '"+modalitaPagamento+"'"
                            + " WHERE ID = '"+id+"' AND ATTIVO = 'S'";
                    
                    result = conn.update(query);
                    if (result.equals(UPDATE_OK)) {
                        closeDialog();
                        JOptionPane.showMessageDialog(parentFrame.getFrame(), "Aggiornamento avvenuto correttamente", "OK", JOptionPane.INFORMATION_MESSAGE);
                    }else{
                        closeDialog();
                        JOptionPane.showMessageDialog(parentFrame.getFrame(), "Impossibile aggiornare il cliente", "Attenzione", JOptionPane.ERROR_MESSAGE);
                        conn.close();
                        return;                      
                    }

                }else{
                    //faccio insert
                    query = "INSERT INTO ANAGRAFICA "
                            + "(CAP_AZIENDA,"
                            + "CAP_RL,"
                            + "CODICE_FISCALE,"
                            + "CITTA_AZIENDA,"
                            + "CITTA_RL,"
                            + "NOME_RL,"
                            + "COGNOME_RL,"
                            + "PARTITA_IVA,"
                            + "FAX_AZIENDA,"
                            + "TELEFONO_RL,"
                            + "TELEFONO_AZIENDA,"
                            + "INDIRIZZO_AZIENDA,"
                            + "INDIRIZZO_RL,"
                            + "RAGIONE_SOCIALE,"
                            + "BANCA,"
                            + "MODALITA_PAGAMENTO) VALUES ("
                            + "'"+CAPAzienda+"',"
                            + "'"+CAPRL+"',"
                            + "'"+codiceFiscale+"',"
                            + "'"+cittaAzienda+"',"
                            + "'"+CittaRL+"',"
                            + "'"+nomeRL+"',"
                            + "'"+CognomeRL+"',"
                            + "'"+partitaIVA+"',"
                            + "'"+faxAzienda+"',"
                            + "'"+telefonoRL+"',"
                            + "'"+telefonoAzienda+"',"
                            + "'"+indirizzo+"',"
                            + "'"+indirizzoRL+"',"
                            + "'"+ragioneSociale+"',"
                            + "'"+banca+"',"
                            + "'"+modalitaPagamento+"'"
                            + ");";
                    result = conn.insert(query);
                    if (result.equals(INSERT_OK)) {
                        
                        
                        query = "SELECT * FROM ANAGRAFICA "
                                + "WHERE "
                            + " CAP_AZIENDA = '"+CAPAzienda+"'"
                            + " AND CAP_RL = '"+CAPRL+"'"
                            + " AND CODICE_FISCALE = '"+codiceFiscale+"'"
                            + " AND CITTA_AZIENDA = '"+cittaAzienda+"'"
                            + " AND CITTA_RL = '"+CittaRL+"'"
                            + " AND NOME_RL = '"+nomeRL+"'"
                            + " AND COGNOME_RL= '"+CognomeRL+"'"
                            + " AND PARTITA_IVA = '"+partitaIVA+"'"
                            + " AND FAX_AZIENDA = '"+faxAzienda+"'"
                            + " AND TELEFONO_RL = '"+telefonoRL+"'"
                            + " AND TELEFONO_AZIENDA = '"+telefonoAzienda+"'"
                            + " AND INDIRIZZO_AZIENDA = '"+indirizzo+"'"
                            + " AND INDIRIZZO_RL = '"+indirizzoRL+"'"
                            + " AND RAGIONE_SOCIALE = '"+ragioneSociale+"'"
                            + " AND BANCA = '"+banca+"'"
                                + " AND MODALITA_PAGAMENTO = '"+modalitaPagamento+"'";
                        
                        res = conn.selectSMS(query);
                        
                        if( res.next() ){
                            id = res.getString("ID");
                            if (!id.equals("")) {
                                jTextFieldID.setText(res.getString("ID"));
                                closeDialog();
                                JOptionPane.showMessageDialog(parentFrame.getFrame(), "Inserimento avvenuto correttamente", "OK", JOptionPane.INFORMATION_MESSAGE);
                                
                            }else{
                                closeDialog();
                                JOptionPane.showMessageDialog(parentFrame.getFrame(), "Errore su id nullo", "Attenzione", JOptionPane.ERROR_MESSAGE);
                            }

                        }else{
                            closeDialog();
                            JOptionPane.showMessageDialog(parentFrame.getFrame(), "Inserimento effettuato ma id non creato", "Attenzione", JOptionPane.ERROR_MESSAGE);
                        }
                        
                    
                    }else{
                        closeDialog();
                        JOptionPane.showMessageDialog(parentFrame.getFrame(), "Impossibile inserire nuovo cliente", "Attenzione", JOptionPane.ERROR_MESSAGE);
                        conn.close();
                        return;                      
                    }                    
                    
                }                
            } catch (Exception e) {
                Utils.logError(e, null, true);
                closeDialog();
            }
            //closeDialog();
            conn.close();

        }
    }    
    
}

