/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package erpgest.panels;

import erpgest.utils.Utils;
import erpgest.utils.UtilsGen;
import java.io.FileOutputStream;
import java.io.IOException;
import java.util.Map;
import java.util.Properties;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author SteVid <www.stevid.it>
 */
public class JPanelAmministrazione extends javax.swing.JPanel {

    /**
     * Creates new form JPanelAmministrazione
     */
    public JPanelAmministrazione() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jTextField2 = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jTextField3 = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jTextFieldRagioneSociale = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jTextFieldPartitaIva = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jTextField6 = new javax.swing.JTextField();
        buttonRegistra1 = new javax.swing.JButton();

        setLayout(null);

        jLabel1.setText("jLabel1");
        add(jLabel1);
        jLabel1.setBounds(50, 240, 51, 15);
        add(jTextField1);
        jTextField1.setBounds(190, 240, 190, 23);

        jLabel2.setText("jLabel1");
        add(jLabel2);
        jLabel2.setBounds(50, 190, 51, 15);
        add(jTextField2);
        jTextField2.setBounds(190, 190, 190, 23);

        jLabel3.setText("jLabel1");
        add(jLabel3);
        jLabel3.setBounds(50, 140, 51, 15);
        add(jTextField3);
        jTextField3.setBounds(190, 140, 190, 23);

        jLabel4.setText("jLabel1");
        add(jLabel4);
        jLabel4.setBounds(50, 30, 51, 15);
        add(jTextFieldRagioneSociale);
        jTextFieldRagioneSociale.setBounds(190, 30, 190, 23);

        jLabel5.setText("jLabel1");
        add(jLabel5);
        jLabel5.setBounds(50, 80, 51, 15);

        jTextFieldPartitaIva.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldPartitaIvaActionPerformed(evt);
            }
        });
        add(jTextFieldPartitaIva);
        jTextFieldPartitaIva.setBounds(190, 90, 190, 23);

        jLabel6.setText("jLabel1");
        add(jLabel6);
        jLabel6.setBounds(50, 290, 51, 15);
        add(jTextField6);
        jTextField6.setBounds(190, 290, 190, 23);

        buttonRegistra1.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N
        buttonRegistra1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/erpgest/img/ico/disk.png"))); // NOI18N
        buttonRegistra1.setText("  Salva");
        buttonRegistra1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonRegistra1ActionPerformed(evt);
            }
        });
        add(buttonRegistra1);
        buttonRegistra1.setBounds(390, 330, 120, 30);
    }// </editor-fold>//GEN-END:initComponents

    private void jTextFieldPartitaIvaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldPartitaIvaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldPartitaIvaActionPerformed

    private void buttonRegistra1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonRegistra1ActionPerformed
        Map <String,String> conf = UtilsGen.caricaConfigurazione();
        Properties prop = new Properties();
        
        prop.put("RagioneSociale", jTextFieldRagioneSociale.getText());
        prop.put("PartitaIva", jTextFieldPartitaIva.getText());
        
        prop.putAll(conf);
        try {
            prop.store(new FileOutputStream("./system/sysconf.properties"), null);
        } catch (IOException ex) {
            Utils.logError(ex, "", true);
            System.out.println("KO");
        }
        System.out.println("OK");
    }//GEN-LAST:event_buttonRegistra1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton buttonRegistra;
    public javax.swing.JButton buttonRegistra1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField6;
    private javax.swing.JTextField jTextFieldPartitaIva;
    private javax.swing.JTextField jTextFieldRagioneSociale;
    // End of variables declaration//GEN-END:variables
}
