/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package erpgest.panels;

import erpgest.MainFrame;
import java.text.SimpleDateFormat;
import java.util.Calendar;
import java.util.Date;
import java.util.GregorianCalendar;
import javax.swing.JOptionPane;
import erpgest.utils.ChooseData;

/**
 *
 * @author SteVid <www.stevid.it>
 */
public class JPanelOrdini extends javax.swing.JPanel implements InterfaceCallBackArticoli,InterfaceCallBackClienti{

    SimpleDateFormat formatterData = new SimpleDateFormat("dd/MM/yyyy");
    SimpleDateFormat formatterOre = new SimpleDateFormat("HH:mm");
    SimpleDateFormat formatterOreSecondi = new SimpleDateFormat("HH:mm:ss");
    SimpleDateFormat formatterDataENG = new SimpleDateFormat("yyyy-MM-dd");
    SimpleDateFormat formatterDataAndTimeENG = new SimpleDateFormat("yyyy-MM-dd HH:mm:ss");    

    MainFrame parentFrame ;
    
    String UPDATE_OK = "Aggiornamento effettuato.";
    String INSERT_OK = "Inserimento effettuato.";
    
    public void setParentFrame(MainFrame parent){
        this.parentFrame = parent;
    }    
    
    /**
     * Creates new form JPanelOrdini
     */
    public JPanelOrdini() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTableClienti = new javax.swing.JTable();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTableArticoli = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jButtonScegliData = new javax.swing.JButton();
        jButtonAggiungiTuttiClienti = new javax.swing.JButton();
        jButtonCancellaCliente = new javax.swing.JButton();
        jButtonAggiungliCliente = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jButtonNuovoOrdine = new javax.swing.JButton();
        jButtonAggiungiArticolo = new javax.swing.JButton();
        jButtonRimuoviArticolo = new javax.swing.JButton();

        setLayout(null);

        jTableClienti.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Ragione Sociale", "Partita IVA", "Indirizzo", "Citta"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, true, false, true
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(jTableClienti);
        if (jTableClienti.getColumnModel().getColumnCount() > 0) {
            jTableClienti.getColumnModel().getColumn(0).setPreferredWidth(30);
            jTableClienti.getColumnModel().getColumn(0).setMaxWidth(30);
            jTableClienti.getColumnModel().getColumn(1).setPreferredWidth(350);
            jTableClienti.getColumnModel().getColumn(1).setMaxWidth(400);
            jTableClienti.getColumnModel().getColumn(2).setPreferredWidth(100);
            jTableClienti.getColumnModel().getColumn(2).setMaxWidth(100);
            jTableClienti.getColumnModel().getColumn(4).setPreferredWidth(100);
            jTableClienti.getColumnModel().getColumn(4).setMaxWidth(100);
        }

        add(jScrollPane1);
        jScrollPane1.setBounds(50, 100, 970, 190);

        jTableArticoli.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Nome", "Descrizione", "Listino", "Prezzo", "Colli"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane2.setViewportView(jTableArticoli);
        if (jTableArticoli.getColumnModel().getColumnCount() > 0) {
            jTableArticoli.getColumnModel().getColumn(0).setPreferredWidth(60);
            jTableArticoli.getColumnModel().getColumn(0).setMaxWidth(60);
            jTableArticoli.getColumnModel().getColumn(1).setPreferredWidth(200);
            jTableArticoli.getColumnModel().getColumn(1).setMaxWidth(200);
            jTableArticoli.getColumnModel().getColumn(2).setPreferredWidth(300);
            jTableArticoli.getColumnModel().getColumn(2).setMaxWidth(350);
            jTableArticoli.getColumnModel().getColumn(3).setPreferredWidth(100);
            jTableArticoli.getColumnModel().getColumn(3).setMaxWidth(100);
            jTableArticoli.getColumnModel().getColumn(4).setPreferredWidth(100);
            jTableArticoli.getColumnModel().getColumn(4).setMaxWidth(100);
        }

        add(jScrollPane2);
        jScrollPane2.setBounds(50, 310, 880, 310);

        jLabel1.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N
        jLabel1.setText("Data Ordine:");
        add(jLabel1);
        jLabel1.setBounds(60, 50, 90, 18);

        jButtonScegliData.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N
        jButtonScegliData.setIcon(new javax.swing.ImageIcon(getClass().getResource("/erpgest/img/ico/calendar_1.png"))); // NOI18N
        jButtonScegliData.setText("Scegli Data");
        jButtonScegliData.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonScegliDataActionPerformed(evt);
            }
        });
        add(jButtonScegliData);
        jButtonScegliData.setBounds(150, 40, 150, 40);

        jButtonAggiungiTuttiClienti.setIcon(new javax.swing.ImageIcon(getClass().getResource("/erpgest/images/add_all.png"))); // NOI18N
        add(jButtonAggiungiTuttiClienti);
        jButtonAggiungiTuttiClienti.setBounds(830, 60, 70, 32);

        jButtonCancellaCliente.setIcon(new javax.swing.ImageIcon(getClass().getResource("/erpgest/img/ico/cross.png"))); // NOI18N
        add(jButtonCancellaCliente);
        jButtonCancellaCliente.setBounds(970, 60, 40, 32);

        jButtonAggiungliCliente.setIcon(new javax.swing.ImageIcon(getClass().getResource("/erpgest/images/add_user.png"))); // NOI18N
        add(jButtonAggiungliCliente);
        jButtonAggiungliCliente.setBounds(900, 60, 70, 32);

        jLabel2.setText("ID");
        add(jLabel2);
        jLabel2.setBounds(10, 10, 20, 15);

        jLabel3.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N
        jLabel3.setText("-");
        add(jLabel3);
        jLabel3.setBounds(40, 10, 50, 15);

        jButtonNuovoOrdine.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N
        jButtonNuovoOrdine.setIcon(new javax.swing.ImageIcon(getClass().getResource("/erpgest/img/ico/note.png"))); // NOI18N
        jButtonNuovoOrdine.setText("Nuovo");
        add(jButtonNuovoOrdine);
        jButtonNuovoOrdine.setBounds(310, 40, 90, 40);

        jButtonAggiungiArticolo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/erpgest/img/ico/add.png"))); // NOI18N
        add(jButtonAggiungiArticolo);
        jButtonAggiungiArticolo.setBounds(940, 330, 40, 31);

        jButtonRimuoviArticolo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/erpgest/img/ico/minus2.png"))); // NOI18N
        jButtonRimuoviArticolo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonRimuoviArticoloActionPerformed(evt);
            }
        });
        add(jButtonRimuoviArticolo);
        jButtonRimuoviArticolo.setBounds(940, 370, 40, 31);
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonScegliDataActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonScegliDataActionPerformed
        GregorianCalendar date = new GregorianCalendar();
        Date dal;
        Date al;
        Date oggi = (Calendar.getInstance()).getTime();
        String strOggi = formatterData.format(oggi);          
        ChooseData dc = new ChooseData(parentFrame, date);
        String choosed = dc.getDate();
        if( choosed.equals("") || choosed == null){
            choosed = "Fino Al ...";
        }
        try {
            al = formatterData.parse(choosed);
        } catch (Exception e) {
        }
    }//GEN-LAST:event_jButtonScegliDataActionPerformed

    private void jButtonRimuoviArticoloActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonRimuoviArticoloActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonRimuoviArticoloActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonAggiungiArticolo;
    private javax.swing.JButton jButtonAggiungiTuttiClienti;
    private javax.swing.JButton jButtonAggiungliCliente;
    private javax.swing.JButton jButtonCancellaCliente;
    private javax.swing.JButton jButtonNuovoOrdine;
    private javax.swing.JButton jButtonRimuoviArticolo;
    private javax.swing.JButton jButtonScegliData;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTableArticoli;
    private javax.swing.JTable jTableClienti;
    // End of variables declaration//GEN-END:variables

    @Override
    public void aggiornaListaArticoli(String id) {
        
    }

    @Override
    public void aggiornaListaClienti(String id) {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }
}
