/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package erpgest.panels;

import erpgest.MainFrame;
import java.sql.ResultSet;
import java.text.SimpleDateFormat;
import java.util.Calendar;
import javax.swing.JOptionPane;

/**
 *
 * @author SteVid <www.stevid.it>
 */
public class JPanelAnagrafica extends javax.swing.JPanel {

    SimpleDateFormat formatterData = new SimpleDateFormat("dd/MM/yyyy");
    SimpleDateFormat formatterOre = new SimpleDateFormat("HH:mm");
    SimpleDateFormat formatterOreSecondi = new SimpleDateFormat("HH:mm:ss");
    SimpleDateFormat formatterDataENG = new SimpleDateFormat("yyyy-MM-dd");
    SimpleDateFormat formatterDataAndTimeENG = new SimpleDateFormat("yyyy-MM-dd HH:mm:ss");  
    MainFrame parentFrame ;
    
    public void setParentFrame(MainFrame parent){
        this.parentFrame = parent;
    }
    
    /**
     * Creates new form JPanelAnagrafica
     */
    public JPanelAnagrafica() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonRegistra = new javax.swing.JButton();
        buttonRicerca2 = new javax.swing.JButton();
        buttonRipulisci = new javax.swing.JButton();
        jButtonAggiorna = new javax.swing.JButton();
        buttonNuovoCliente = new javax.swing.JButton();
        ID = new javax.swing.JTextField();
        buttonElimina = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jLabel50 = new javax.swing.JLabel();
        jTextFieldIndirizzo = new javax.swing.JTextField();
        jLabel52 = new javax.swing.JLabel();
        jTextFieldTelefono = new javax.swing.JTextField();
        jLabel54 = new javax.swing.JLabel();
        jTextFieldCAP = new javax.swing.JTextField();
        jLabel55 = new javax.swing.JLabel();
        jTextFieldCittaAzienda = new javax.swing.JTextField();
        jLabel51 = new javax.swing.JLabel();
        jTextFieldRagioneSociale = new javax.swing.JTextField();
        jTextFieldFax = new javax.swing.JTextField();
        jLabel56 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jTextFieldPartitaIVA = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        jLabel49 = new javax.swing.JLabel();
        jTextFieldNome = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jTextFieldCognome = new javax.swing.JTextField();
        jLabel53 = new javax.swing.JLabel();
        jTextFieldCittaRL = new javax.swing.JTextField();
        jLabel20 = new javax.swing.JLabel();
        jTextFieldCF = new javax.swing.JTextField();
        jLabel58 = new javax.swing.JLabel();
        jLabel57 = new javax.swing.JLabel();
        jTextFieldTelefonoRL = new javax.swing.JTextField();
        jTextFieldCAPRL = new javax.swing.JTextField();
        jLabel59 = new javax.swing.JLabel();
        jTextFieldIndirizzoRL = new javax.swing.JTextField();

        setBorder(javax.swing.BorderFactory.createTitledBorder("Clienti"));
        setLayout(null);

        buttonRegistra.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N
        buttonRegistra.setIcon(new javax.swing.ImageIcon(getClass().getResource("/erpgest/img/ico/disk.png"))); // NOI18N
        buttonRegistra.setText("  Salva");
        buttonRegistra.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonRegistraActionPerformed(evt);
            }
        });
        add(buttonRegistra);
        buttonRegistra.setBounds(370, 40, 120, 30);

        buttonRicerca2.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N
        buttonRicerca2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/erpgest/img/ico/drawer.png"))); // NOI18N
        buttonRicerca2.setText("ricerca");
        buttonRicerca2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonRicerca2ActionPerformed(evt);
            }
        });
        add(buttonRicerca2);
        buttonRicerca2.setBounds(260, 40, 100, 30);

        buttonRipulisci.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N
        buttonRipulisci.setText("Azzera Campi");
        buttonRipulisci.setToolTipText("Azzera tutti i dati");
        buttonRipulisci.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonRipulisciActionPerformed(evt);
            }
        });
        add(buttonRipulisci);
        buttonRipulisci.setBounds(500, 40, 150, 30);

        jButtonAggiorna.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N
        jButtonAggiorna.setIcon(new javax.swing.ImageIcon(getClass().getResource("/erpgest/img/ico/arrow_refresh.png"))); // NOI18N
        jButtonAggiorna.setText("Aggiorna");
        jButtonAggiorna.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                jButtonAggiornaMouseReleased(evt);
            }
        });
        add(jButtonAggiorna);
        jButtonAggiorna.setBounds(670, 40, 110, 30);

        buttonNuovoCliente.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N
        buttonNuovoCliente.setIcon(new javax.swing.ImageIcon(getClass().getResource("/erpgest/img/ico/user.png"))); // NOI18N
        buttonNuovoCliente.setText("Nuovo Cliente");
        buttonNuovoCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonNuovoClienteActionPerformed(evt);
            }
        });
        add(buttonNuovoCliente);
        buttonNuovoCliente.setBounds(860, 40, 150, 30);

        ID.setEditable(false);
        ID.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        ID.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        add(ID);
        ID.setBounds(30, 40, 90, 35);

        buttonElimina.setIcon(new javax.swing.ImageIcon(getClass().getResource("/erpgest/img/ico/cancel.png"))); // NOI18N
        buttonElimina.setText("Elimina");
        buttonElimina.setToolTipText("Cancella il cliente indicato");
        buttonElimina.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                buttonEliminaMouseReleased(evt);
            }
        });
        add(buttonElimina);
        buttonElimina.setBounds(130, 40, 110, 30);

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Dati Azienda"));
        jPanel1.setLayout(null);

        jLabel50.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N
        jLabel50.setText("Indirizzo");
        jPanel1.add(jLabel50);
        jLabel50.setBounds(20, 110, 260, 20);

        jTextFieldIndirizzo.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jTextFieldIndirizzo.setForeground(new java.awt.Color(0, 0, 204));
        jPanel1.add(jTextFieldIndirizzo);
        jTextFieldIndirizzo.setBounds(20, 130, 260, 30);

        jLabel52.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N
        jLabel52.setText("Telefono");
        jPanel1.add(jLabel52);
        jLabel52.setBounds(680, 110, 130, 20);

        jTextFieldTelefono.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jTextFieldTelefono.setForeground(new java.awt.Color(0, 0, 204));
        jPanel1.add(jTextFieldTelefono);
        jTextFieldTelefono.setBounds(680, 130, 130, 30);

        jLabel54.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N
        jLabel54.setText("CAP");
        jPanel1.add(jLabel54);
        jLabel54.setBounds(560, 110, 110, 20);

        jTextFieldCAP.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jTextFieldCAP.setForeground(new java.awt.Color(0, 0, 204));
        jPanel1.add(jTextFieldCAP);
        jTextFieldCAP.setBounds(560, 130, 110, 30);

        jLabel55.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N
        jLabel55.setText("Città");
        jPanel1.add(jLabel55);
        jLabel55.setBounds(290, 110, 260, 20);

        jTextFieldCittaAzienda.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jTextFieldCittaAzienda.setForeground(new java.awt.Color(0, 0, 204));
        jPanel1.add(jTextFieldCittaAzienda);
        jTextFieldCittaAzienda.setBounds(290, 130, 260, 30);

        jLabel51.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N
        jLabel51.setText("Ragione Sociale");
        jPanel1.add(jLabel51);
        jLabel51.setBounds(20, 20, 130, 20);

        jTextFieldRagioneSociale.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jTextFieldRagioneSociale.setForeground(new java.awt.Color(0, 0, 204));
        jPanel1.add(jTextFieldRagioneSociale);
        jTextFieldRagioneSociale.setBounds(20, 40, 260, 30);

        jTextFieldFax.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jTextFieldFax.setForeground(new java.awt.Color(0, 0, 204));
        jPanel1.add(jTextFieldFax);
        jTextFieldFax.setBounds(820, 130, 130, 30);

        jLabel56.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N
        jLabel56.setText("FAX");
        jPanel1.add(jLabel56);
        jLabel56.setBounds(820, 110, 130, 20);

        jLabel21.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N
        jLabel21.setText("Partita IVA");
        jPanel1.add(jLabel21);
        jLabel21.setBounds(290, 20, 220, 20);

        jTextFieldPartitaIVA.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jTextFieldPartitaIVA.setForeground(new java.awt.Color(0, 0, 204));
        jPanel1.add(jTextFieldPartitaIVA);
        jTextFieldPartitaIVA.setBounds(290, 40, 340, 30);

        add(jPanel1);
        jPanel1.setBounds(30, 100, 1040, 180);

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder("Referente Legale"));
        jPanel2.setLayout(null);

        jLabel49.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N
        jLabel49.setText("Nome");
        jPanel2.add(jLabel49);
        jLabel49.setBounds(20, 20, 90, 20);

        jTextFieldNome.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jTextFieldNome.setForeground(new java.awt.Color(0, 0, 204));
        jPanel2.add(jTextFieldNome);
        jTextFieldNome.setBounds(20, 40, 260, 30);

        jLabel5.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N
        jLabel5.setText("Cognome");
        jPanel2.add(jLabel5);
        jLabel5.setBounds(290, 20, 100, 20);

        jTextFieldCognome.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jTextFieldCognome.setForeground(new java.awt.Color(0, 0, 204));
        jPanel2.add(jTextFieldCognome);
        jTextFieldCognome.setBounds(290, 40, 280, 30);

        jLabel53.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N
        jLabel53.setText("Città");
        jPanel2.add(jLabel53);
        jLabel53.setBounds(290, 110, 260, 20);

        jTextFieldCittaRL.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jTextFieldCittaRL.setForeground(new java.awt.Color(0, 0, 204));
        jPanel2.add(jTextFieldCittaRL);
        jTextFieldCittaRL.setBounds(290, 130, 260, 30);

        jLabel20.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N
        jLabel20.setText("Codice Fiscale");
        jPanel2.add(jLabel20);
        jLabel20.setBounds(820, 110, 200, 20);

        jTextFieldCF.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jTextFieldCF.setForeground(new java.awt.Color(0, 0, 204));
        jPanel2.add(jTextFieldCF);
        jTextFieldCF.setBounds(820, 130, 200, 30);

        jLabel58.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N
        jLabel58.setText("Telefono");
        jPanel2.add(jLabel58);
        jLabel58.setBounds(680, 110, 130, 20);

        jLabel57.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N
        jLabel57.setText("CAP");
        jPanel2.add(jLabel57);
        jLabel57.setBounds(560, 110, 110, 20);

        jTextFieldTelefonoRL.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jTextFieldTelefonoRL.setForeground(new java.awt.Color(0, 0, 204));
        jPanel2.add(jTextFieldTelefonoRL);
        jTextFieldTelefonoRL.setBounds(680, 130, 130, 30);

        jTextFieldCAPRL.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jTextFieldCAPRL.setForeground(new java.awt.Color(0, 0, 204));
        jPanel2.add(jTextFieldCAPRL);
        jTextFieldCAPRL.setBounds(560, 130, 110, 30);

        jLabel59.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N
        jLabel59.setText("Indirizzo");
        jPanel2.add(jLabel59);
        jLabel59.setBounds(20, 110, 260, 20);

        jTextFieldIndirizzoRL.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jTextFieldIndirizzoRL.setForeground(new java.awt.Color(0, 0, 204));
        jPanel2.add(jTextFieldIndirizzoRL);
        jTextFieldIndirizzoRL.setBounds(20, 130, 260, 30);

        add(jPanel2);
        jPanel2.setBounds(30, 300, 1040, 170);
    }// </editor-fold>//GEN-END:initComponents

    private void buttonRegistraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonRegistraActionPerformed

        Calendar cal = Calendar.getInstance();
        String query;
        String strDate = formatterDataAndTimeENG.format(cal.getTime());
        String nomeStr = (jTextFieldNome.getText()).toUpperCase().replaceAll("'", "''");
        String cognomeStr = (jTextFieldCognome.getText()).toUpperCase().replaceAll("'", "''");
        String codiceFiscaleStr = (jTextFieldCF.getText()).toUpperCase().replaceAll("'", "''");


        String returnStr = "";

        ResultSet res = null;
        int i = 0;

        if (nomeStr.equals("")
            || nomeStr == null
            || cognomeStr.equals("")
            || cognomeStr == null //|| codiceFiscaleStr.equals("")
            //|| codiceFiscaleStr == null
        ) {

            JOptionPane.showMessageDialog(parentFrame.getFrame(), "Errore Nome,Cognome sono obbligatori", "Attenzione", JOptionPane.ERROR_MESSAGE);
            parentFrame.closeDialog();
            return;
        }

        //lancio il thread per la lettura e l'apertura della porta
        Thread t = new Thread(new erpgest.utils.ShowWaiting(parentFrame.getFrame(), null, "Salvataggio in corso. Attendere"));
        t.start();

        while (parentFrame.waiting == null) {
            try {
                Thread.sleep(100);
            } catch (Exception e) {
            }
        }

        Thread tt = new Thread(new SalvaDatiNelDB());
        tt.start();
    }//GEN-LAST:event_buttonRegistraActionPerformed

    private void buttonRicerca2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonRicerca2ActionPerformed
        JPanelRicercaClienti dialog = new JPanelRicercaClienti(this.parentFrame);
    }//GEN-LAST:event_buttonRicerca2ActionPerformed

    private void buttonRipulisciActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonRipulisciActionPerformed
        azzeraCampi();
    }//GEN-LAST:event_buttonRipulisciActionPerformed

    private void jButtonAggiornaMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonAggiornaMouseReleased
        String id = ID.getText();
        int _id = 0;
        if (!id.equals("") && !id.equals("-")) {
            _id = Integer.parseInt(id);
        }

        aggiornaFinestraInserimentoCliente(_id);
    }//GEN-LAST:event_jButtonAggiornaMouseReleased

    private void buttonNuovoClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonNuovoClienteActionPerformed
        azzeraCampi();
    }//GEN-LAST:event_buttonNuovoClienteActionPerformed

    private void buttonEliminaMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_buttonEliminaMouseReleased
        if (ID.getText().equals("") || ID.getText().equals("-")) {
            JOptionPane.showMessageDialog(this, "Cliente Selezionato Non disponibile o mancante.", "Attenzione", JOptionPane.ERROR_MESSAGE);
            return;
        }

        int n = JOptionPane.showConfirmDialog(null,
            "ATTENZIONE!! Si vuole cancellare il cliente "+ jTextFieldNome.getText()+","+jTextFieldCognome.getText() +"?",
            "",
            JOptionPane.YES_NO_OPTION);

        if (n == JOptionPane.YES_OPTION) {
            //JOptionPane.showMessageDialog(null, "Opening...");
            disabilitaUtente(ID.getText());
        } else {
            //JOptionPane.showMessageDialog(null, "Goodbye");
            return;
        }
    }//GEN-LAST:event_buttonEliminaMouseReleased


    public void aggiornaFinestraInserimentoCliente(int id){
        
        
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JTextField ID;
    public javax.swing.JButton buttonElimina;
    public javax.swing.JButton buttonNuovoCliente;
    public javax.swing.JButton buttonRegistra;
    public javax.swing.JButton buttonRicerca2;
    public javax.swing.JButton buttonRipulisci;
    private javax.swing.JButton jButtonAggiorna;
    public javax.swing.JLabel jLabel20;
    public javax.swing.JLabel jLabel21;
    public javax.swing.JLabel jLabel49;
    public javax.swing.JLabel jLabel5;
    public javax.swing.JLabel jLabel50;
    public javax.swing.JLabel jLabel51;
    public javax.swing.JLabel jLabel52;
    public javax.swing.JLabel jLabel53;
    public javax.swing.JLabel jLabel54;
    public javax.swing.JLabel jLabel55;
    public javax.swing.JLabel jLabel56;
    public javax.swing.JLabel jLabel57;
    public javax.swing.JLabel jLabel58;
    public javax.swing.JLabel jLabel59;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    public javax.swing.JTextField jTextFieldCAP;
    public javax.swing.JTextField jTextFieldCAPRL;
    public javax.swing.JTextField jTextFieldCF;
    public javax.swing.JTextField jTextFieldCittaAzienda;
    public javax.swing.JTextField jTextFieldCittaRL;
    public javax.swing.JTextField jTextFieldCognome;
    public javax.swing.JTextField jTextFieldFax;
    public javax.swing.JTextField jTextFieldIndirizzo;
    public javax.swing.JTextField jTextFieldIndirizzoRL;
    public javax.swing.JTextField jTextFieldNome;
    public javax.swing.JTextField jTextFieldPartitaIVA;
    public javax.swing.JTextField jTextFieldRagioneSociale;
    public javax.swing.JTextField jTextFieldTelefono;
    public javax.swing.JTextField jTextFieldTelefonoRL;
    // End of variables declaration//GEN-END:variables

    private void azzeraCampi() {
        
    }

    private void disabilitaUtente(String text) {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }
}

class SalvaDatiNelDB implements Runnable {

    @Override
    public void run() {

    }
}