/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package erpgest;

/**
 *
 * @author stefano
 */
public class MainFrame extends javax.swing.JFrame {

    public static erpgest.utils.Waiting waiting;
    
    public static erpgest.utils.Waiting2 waiting2;    
    
    /**
     * Creates new form MainFrame
     */
    public MainFrame() {
        initComponents();
        jPanelAnagrafica1.setParentFrame(this);
        jPanelArticoli1.setParentFrame(this);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane2 = new javax.swing.JTabbedPane();
        jPanelAnagrafica1 = new erpgest.panels.JPanelAnagrafica();
        jPanelArticoli1 = new erpgest.panels.JPanelArticoli();
        jPanelListinoPrezzi1 = new erpgest.panels.JPanelListinoPrezzi();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jTabbedPane2.addTab("Anagrafica", jPanelAnagrafica1);

        javax.swing.GroupLayout jPanelArticoli1Layout = new javax.swing.GroupLayout(jPanelArticoli1);
        jPanelArticoli1.setLayout(jPanelArticoli1Layout);
        jPanelArticoli1Layout.setHorizontalGroup(
            jPanelArticoli1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1132, Short.MAX_VALUE)
        );
        jPanelArticoli1Layout.setVerticalGroup(
            jPanelArticoli1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 646, Short.MAX_VALUE)
        );

        jTabbedPane2.addTab("Articoli", jPanelArticoli1);
        jTabbedPane2.addTab("Listini e Prezzi", jPanelListinoPrezzi1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane2)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane2)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainFrame().setVisible(true);
            }
        });
    }

    public MainFrame getFrame() {
        return this;
    }
    
    public void closeDialog() {
        if (waiting != null) {
            waiting.dispose();
            waiting = null;
            validate();
            repaint();
        }

    }    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private erpgest.panels.JPanelAnagrafica jPanelAnagrafica1;
    private erpgest.panels.JPanelArticoli jPanelArticoli1;
    private erpgest.panels.JPanelListinoPrezzi jPanelListinoPrezzi1;
    private javax.swing.JTabbedPane jTabbedPane2;
    // End of variables declaration//GEN-END:variables
}
